<?
/**
 * @var CMain $APPLICATION
 */
require($_SERVER["DOCUMENT_ROOT"] . "/bitrix/header.php");
$APPLICATION->SetTitle("Каталог");

$request = \Bitrix\Main\Context::getCurrent()->getRequest();
$catalogTypeFilter = $request->get('brandType');

global $catalogFilter;
if ($catalogTypeFilter != 0) {
    $catalogFilter['PROPERTY_TYPE'] = $catalogTypeFilter;
}

$componentPropertiesSelect = \BH\Model\Catalog::getComponentPropertiesSelect();
?>

    <div class="container">

        <?
        $APPLICATION->IncludeComponent(
            "bitrix:catalog",
            "catalog",
            array(
                "ACTIVE_DATE_FORMAT" => "d.m.Y",
                "ADD_ELEMENT_CHAIN" => "N",
                "ADD_SECTIONS_CHAIN" => "N",
                "AJAX_MODE" => "N",
                "AJAX_OPTION_ADDITIONAL" => "",
                "AJAX_OPTION_HISTORY" => "N",
                "AJAX_OPTION_JUMP" => "N",
                "AJAX_OPTION_STYLE" => "Y",
                "BROWSER_TITLE" => "NAME",
                "CACHE_FILTER" => "N",
                "CACHE_GROUPS" => "N",
                "CACHE_TIME" => "0",
                "CACHE_TYPE" => "N",
                "CHECK_DATES" => "Y",
                "DETAIL_ACTIVE_DATE_FORMAT" => "d.m.Y",
                "DETAIL_DISPLAY_BOTTOM_PAGER" => "Y",
                "DETAIL_DISPLAY_TOP_PAGER" => "N",
                "DETAIL_FIELD_CODE" => "",
                "DETAIL_PAGER_SHOW_ALL" => "Y",
                "DETAIL_PAGER_TEMPLATE" => "",
                "DETAIL_PAGER_TITLE" => "Страница",
                "DETAIL_PROPERTY_CODE" => \BH\Model\Brand::getComponentPropertiesSelect(),
                "DETAIL_SET_CANONICAL_URL" => "N",
                "DETAIL_URL" => "",
                "DISPLAY_BOTTOM_PAGER" => "Y",
                "DISPLAY_DATE" => "Y",
                "DISPLAY_NAME" => "Y",
                "DISPLAY_PICTURE" => "Y",
                "DISPLAY_PREVIEW_TEXT" => "Y",
                "DISPLAY_TOP_PAGER" => "Y",
                "FIELD_CODE" => "",
                "FILTER_NAME" => "catalogFilter",
                "HIDE_LINK_WHEN_NO_DETAIL" => "N",
                "IBLOCK_ID" => \BH\Model\Catalog::IBLOCK_ID,
                "IBLOCK_TYPE" => "catalog",
                "INCLUDE_IBLOCK_INTO_CHAIN" => "N",
                "INCLUDE_SUBSECTIONS" => "N",
                "LIST_ACTIVE_DATE_FORMAT" => "d.m.Y",
                "LIST_FIELD_CODE" => "",
                "LIST_PROPERTY_CODE" => $componentPropertiesSelect,
                "MESSAGE_404" => "",
                "META_DESCRIPTION" => "-",
                "META_KEYWORDS" => "-",
                "NEWS_COUNT" => "10",
                "PAGER_BASE_LINK_ENABLE" => "N",
                "PAGER_DESC_NUMBERING" => "N",
                "PAGER_DESC_NUMBERING_CACHE_TIME" => "0",
                "PAGER_SHOW_ALL" => "N",
                "PAGER_SHOW_ALWAYS" => "N",
                "PAGER_TEMPLATE" => "elements-pager",
                "PAGER_TITLE" => "Новости",
                "PARENT_SECTION" => "",
                "PARENT_SECTION_CODE" => "",
                "PREVIEW_TRUNCATE_LEN" => "",
                "PROPERTY_CODE" => $componentPropertiesSelect,
                "SEF_FOLDER" => "/catalog/",
                "SEF_MODE" => "Y",
                "SET_BROWSER_TITLE" => "Y",
                "SET_LAST_MODIFIED" => "Y",
                "SET_META_DESCRIPTION" => "Y",
                "SET_META_KEYWORDS" => "Y",
                "SET_STATUS_404" => "N",
                "SET_TITLE" => "Y",
                "SHARE_HANDLERS" => "vk",
                "SHARE_HIDE" => "N",
                "SHARE_SHORTEN_URL_KEY" => "",
                "SHARE_SHORTEN_URL_LOGIN" => "",
                "SHARE_TEMPLATE" => "",
                "SHOW_404" => "N",
                "SORT_BY1" => "ACTIVE_FROM",
                "SORT_BY2" => "SORT",
                "SORT_ORDER1" => "DESC",
                "SORT_ORDER2" => "ASC",
                "USE_AD" => "Y",
                "USE_CATEGORIES" => "N",
                "USE_FILTER" => "N",
                "USE_PERMISSIONS" => "N",
                "USE_RATING" => "N",
                "USE_REVIEW" => "Y",
                "USE_RSS" => "N",
                "USE_SEARCH" => "Y",
                "USE_SHARE" => "Y",
                "USE_SUGGEST" => "Y",
                "COMPONENT_TEMPLATE" => ".default",
                "HIDE_NOT_AVAILABLE" => "N",
                "TEMPLATE_THEME" => "blue",
                "ADD_PICT_PROP" => "-",
                "LABEL_PROP" => "-",
                "COMMON_SHOW_CLOSE_POPUP" => "N",
                "SHOW_DISCOUNT_PERCENT" => "N",
                "SHOW_OLD_PRICE" => "N",
                "DETAIL_SHOW_MAX_QUANTITY" => "N",
                "MESS_BTN_BUY" => "Купить",
                "MESS_BTN_ADD_TO_BASKET" => "В корзину",
                "MESS_BTN_COMPARE" => "Сравнение",
                "MESS_BTN_DETAIL" => "Подробнее",
                "MESS_NOT_AVAILABLE" => "Нет в наличии",
                "DETAIL_USE_VOTE_RATING" => "N",
                "DETAIL_USE_COMMENTS" => "N",
                "SIDEBAR_SECTION_SHOW" => "Y",
                "SIDEBAR_DETAIL_SHOW" => "Y",
                "SIDEBAR_PATH" => "",
                "USE_MAIN_ELEMENT_SECTION" => "N",
                "USE_ELEMENT_COUNTER" => "Y",
                "USE_SALE_BESTSELLERS" => "Y",
                "FILTER_FIELD_CODE" => array(
                    0 => "ID",
                    1 => "",
                ),
                "FILTER_PROPERTY_CODE" => array(
                    0 => "",
                    1 => "",
                ),
                "FILTER_PRICE_CODE" => array(
                    0 => "BASE",
                ),
                "FILTER_VIEW_MODE" => "VERTICAL",
                "MESSAGES_PER_PAGE" => "10",
                "USE_CAPTCHA" => "Y",
                "REVIEW_AJAX_POST" => "Y",
                "PATH_TO_SMILE" => "/bitrix/images/forum/smile/",
                "FORUM_ID" => "3",
                "URL_TEMPLATES_READ" => "",
                "SHOW_LINK_TO_FORUM" => "Y",
                "ACTION_VARIABLE" => "action",
                "PRODUCT_ID_VARIABLE" => "id",
                "USE_COMPARE" => "N",
                "PRICE_CODE" => array(
                    0 => "BASE",
                ),
                "USE_PRICE_COUNT" => "N",
                "SHOW_PRICE_COUNT" => "1",
                "PRICE_VAT_INCLUDE" => "Y",
                "PRICE_VAT_SHOW_VALUE" => "N",
                "CONVERT_CURRENCY" => "N",
                "BASKET_URL" => "/personal/basket.php",
                "USE_PRODUCT_QUANTITY" => "N",
                "PRODUCT_QUANTITY_VARIABLE" => "",
                "ADD_PROPERTIES_TO_BASKET" => "Y",
                "PRODUCT_PROPS_VARIABLE" => "prop",
                "PARTIAL_PRODUCT_PROPERTIES" => "N",
                "PRODUCT_PROPERTIES" => array(),
                "USE_COMMON_SETTINGS_BASKET_POPUP" => "N",
                "COMMON_ADD_TO_BASKET_ACTION" => "",
                "TOP_ADD_TO_BASKET_ACTION" => "ADD",
                "SECTION_ADD_TO_BASKET_ACTION" => "ADD",
                "DETAIL_ADD_TO_BASKET_ACTION" => array(
                    0 => "ADD",
                ),
                "SHOW_TOP_ELEMENTS" => "N",
                "SECTION_COUNT_ELEMENTS" => "Y",
                "SECTION_TOP_DEPTH" => "1",
                "SECTIONS_VIEW_MODE" => "LIST",
                "SECTIONS_SHOW_PARENT_NAME" => "Y",
                "PAGE_ELEMENT_COUNT" => "30",
                "LINE_ELEMENT_COUNT" => "3",
                "ELEMENT_SORT_FIELD" => "sort",
                "ELEMENT_SORT_ORDER" => "asc",
                "ELEMENT_SORT_FIELD2" => "id",
                "ELEMENT_SORT_ORDER2" => "desc",
                "LIST_META_KEYWORDS" => "-",
                "LIST_META_DESCRIPTION" => "-",
                "LIST_BROWSER_TITLE" => "-",
                "SECTION_BACKGROUND_IMAGE" => "-",
                "DETAIL_META_KEYWORDS" => "-",
                "DETAIL_META_DESCRIPTION" => "-",
                "DETAIL_BROWSER_TITLE" => "-",
                "SECTION_ID_VARIABLE" => "SECTION_ID",
                "DETAIL_CHECK_SECTION_ID_VARIABLE" => "N",
                "DETAIL_BACKGROUND_IMAGE" => "-",
                "SHOW_DEACTIVATED" => "N",
                "DETAIL_DISPLAY_NAME" => "Y",
                "DETAIL_DETAIL_PICTURE_MODE" => "IMG",
                "DETAIL_ADD_DETAIL_TO_SLIDER" => "N",
                "DETAIL_DISPLAY_PREVIEW_TEXT_MODE" => "E",
                "LINK_IBLOCK_TYPE" => "",
                "LINK_IBLOCK_ID" => "",
                "LINK_PROPERTY_SID" => "",
                "LINK_ELEMENTS_URL" => "link.php?PARENT_ELEMENT_ID=#ELEMENT_ID#",
                "USE_ALSO_BUY" => "N",
                "USE_STORE" => "N",
                "USE_BIG_DATA" => "Y",
                "BIG_DATA_RCM_TYPE" => "bestsell",
                "SECTION_FIELDS" => array(0 => "UF_*", 1 => 'PICTURE'),
                "SEF_URL_TEMPLATES" => array(
                    "sections" => "/",
                    "section" => "#SECTION_CODE#/",
                    "element" => "#SECTION_ID#/#ELEMENT_CODE#/",
                    "compare" => "compare.php?action=#ACTION_CODE#",
                    "smart_filter" => "#SECTION_CODE#/filter/#SMART_FILTER_PATH#/apply/",
                ),
                "VARIABLE_ALIASES" => array(
                    "compare" => array(
                        "ACTION_CODE" => "action",
                    ),
                ),
                'OFFERS_FIELD_CODE' => array('ID', 'IBLOCK_ID', 'NAME', 'CODE'),
                'OFFERS_PROPERTY_CODE' => $componentPropertiesSelect
            ),
            false
        ); ?>

    </div>

<? require($_SERVER["DOCUMENT_ROOT"] . "/bitrix/footer.php"); ?>